# Project config #
project_name: 'cifar-demo'
log_level: INFO

# Worker config #
# Additional definition for the worker can be found here: https://docker-py.readthedocs.io/en/stable/containers.html

#ram: # Accepts int values (which represent the memory limit of the created container in bytes)
#num_gpus: # A non-zero value mounts all available GPUs inside the worker

#worker:
#  image:  # The worker image will be pulled if it doesn't exist. :latest will be pulled if no tag is specified.
#  entrypoint: # Will override the entrypoint defined in the worker image
#  command:  # Arguments to be passed to the entrypoint above
#  working_dir:  # Working directory when entering the worker container. Your code will be at /job/job_source
#
#  volumes:
#    volume1: # replace volume1 with path on host machine
#      bind: # path inside the worker container
#      mode: # one of rw, ro
#    volume2:
#      bind:
#      mode:
#
#  environment:
#    variable: value # Set environment variables using key-value pairs